name: CI

on:
  push:
  pull_request:

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config
        
      - name: Build Frontend
        run: docker build -t frontend ./frontend 

      - name: Build Backend
        run: docker build -t backend ./backend

      
      - name: Build Notify
        run: docker build -t notify ./notify