name: CI

on:
  push:
  pull_request:

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Files
        run: ls -la